name: Identity API - Development
values:
  - key: baseUrl
    value: 'https://2f8af71b-92e1-4332-9dfb-c2e72426f4de.mock.pstmn.io'
    enabled: true
  - key: testEmail
    value: dev-bot@acme.io
    enabled: true
  - key: testPassword
    value: DevPassword123!
    enabled: true
  - key: accessToken
    value: ''
    enabled: true
  - key: refreshToken
    value: ''
    enabled: true
  - key: userId
    value: usr_dev_seed_001
    enabled: true
