name: API Governance
on:
  push:
    paths: ['openapi.yaml', 'postman/specs/**']
  pull_request:
    paths: ['openapi.yaml', 'postman/specs/**']
  workflow_dispatch:
jobs:
  governance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli
      - name: Lint OpenAPI Spec
        run: spectral lint openapi.yaml --fail-severity error
        continue-on-error: true
      - name: Install Postman CLI
        run: curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Postman Governance Check
        run: postman spec lint 73a3e8f5-4833-4034-8dba-425e7739a48d --workspace-id 4cfe3128-bf07-46e2-891f-455781bda560
